---

services:
  postgresql:
    image: postgres:17.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
    - "5432:5432"
    volumes:
    - ./initdb:/docker-entrypoint-initdb.d
    - ./data:/var/lib/postgresql/data

networks:
  default:
    name: webbench
