---

services:
  uvicorn:
    build:
      context: python/uvicorn
    environment:
      - WEB_CONCURRENCY=4
      - LOOP=uvloop
      - JSON_LIBRARY=orjson
    ports:
      - "8000:8000"
  uvicorn-one-worker:
    build:
      context: python/uvicorn
    environment:
      - WEB_CONCURRENCY=1
      - LOOP=uvloop
      - JSON_LIBRARY=orjson
    ports:
      - "8000:8000"
  uvicorn-asyncio:
    build:
      context: python/uvicorn
    environment:
      - WEB_CONCURRENCY=4
      - LOOP=asyncio
      - JSON_LIBRARY=orjson
    ports:
      - "8000:8000"
  uvicorn-stdjson:
    build:
      context: python/uvicorn
    environment:
      - WEB_CONCURRENCY=4
      - LOOP=uvloop
      - JSON_LIBRARY=stdlib
    ports:
      - "8000:8000"
  uvicorn-stdlib:
    build:
      context: python/uvicorn
    environment:
      - WEB_CONCURRENCY=4
      - LOOP=asyncio
      - JSON_LIBRARY=stdlib
    ports:
      - "8000:8000"
  uvicorn-stdlib-one-worker:
    build:
      context: python/uvicorn
    environment:
      - WEB_CONCURRENCY=1
      - LOOP=asyncio
      - JSON_LIBRARY=stdlib
    ports:
      - "8000:8000"
