---

services:
  go-stdlib:
    build:
      context: go/stdlib
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8000:8000"
  uvicorn:
    build:
      context: python/uvicorn
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WEB_CONCURRENCY=4
      - LOOP=uvloop
      - HTTP=httptools
      - JSON_LIBRARY=orjson
    ports:
      - "8000:8000"
  uvicorn-h11:
    build:
      context: python/uvicorn
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WEB_CONCURRENCY=4
      - LOOP=uvloop
      - HTTP=h11
      - JSON_LIBRARY=orjson
    ports:
      - "8000:8000"
  uvicorn-one-worker:
    build:
      context: python/uvicorn
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WEB_CONCURRENCY=1
      - LOOP=uvloop
      - HTTP=httptools
      - JSON_LIBRARY=orjson
    ports:
      - "8000:8000"
  uvicorn-asyncio:
    build:
      context: python/uvicorn
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WEB_CONCURRENCY=4
      - LOOP=asyncio
      - HTTP=httptools
      - JSON_LIBRARY=orjson
    ports:
      - "8000:8000"
  uvicorn-stdlib:
    build:
      context: python/uvicorn
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WEB_CONCURRENCY=4
      - LOOP=asyncio
      - HTTP=h11
      - JSON_LIBRARY=stdlib
    ports:
      - "8000:8000"
  uvicorn-stdlib-one-worker:
    build:
      context: python/uvicorn
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WEB_CONCURRENCY=1
      - LOOP=asyncio
      - HTTP=h11
      - JSON_LIBRARY=stdlib
    ports:
      - "8000:8000"
  uvicorn-pypy:
    build:
      context: python/uvicorn
      dockerfile: Dockerfile.pypy
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WEB_CONCURRENCY=4
    ports:
      - "8000:8000"
  fastapi:
    build:
      context: python/fastapi
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8000:8000"
  fastapi-sync-endpoints:
    build:
      context: python/fastapi
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SYNC_ENDPOINTS=1
    ports:
      - "8000:8000"
  fastapi-sync-dependency:
    build:
      context: python/fastapi
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SYNC_DEPENDENCY=1
    ports:
      - "8000:8000"

networks:
  default:
    name: webbench
