---

x-common: &common
  ulimits:
    nofile:
      soft: 1048576
      hard: 1048576
  sysctls:
    - net.core.somaxconn=4096
    - net.ipv4.tcp_max_syn_backlog=2048
  ports:
    - "8000:8000"

services:
  go-stdlib:
    <<: *common
    build:
      context: go/stdlib

  uvicorn:
    <<: *common
    build:
      context: python/uvicorn
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WEB_CONCURRENCY=4
      - LOOP=uvloop
      - HTTP=httptools
      - JSON_LIBRARY=orjson

  uvicorn-h11:
    <<: *common
    build:
      context: python/uvicorn
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WEB_CONCURRENCY=4
      - LOOP=uvloop
      - HTTP=h11
      - JSON_LIBRARY=orjson

  uvicorn-one-worker:
    <<: *common
    build:
      context: python/uvicorn
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WEB_CONCURRENCY=1
      - LOOP=uvloop
      - HTTP=httptools
      - JSON_LIBRARY=orjson

  uvicorn-asyncio:
    <<: *common
    build:
      context: python/uvicorn
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WEB_CONCURRENCY=4
      - LOOP=asyncio
      - HTTP=httptools
      - JSON_LIBRARY=orjson

  uvicorn-stdlib:
    <<: *common
    build:
      context: python/uvicorn
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WEB_CONCURRENCY=4
      - LOOP=asyncio
      - HTTP=h11
      - JSON_LIBRARY=stdlib

  uvicorn-stdlib-one-worker:
    <<: *common
    build:
      context: python/uvicorn
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WEB_CONCURRENCY=1
      - LOOP=asyncio
      - HTTP=h11
      - JSON_LIBRARY=stdlib

  uvicorn-pypy:
    <<: *common
    build:
      context: python/uvicorn
      dockerfile: Dockerfile.pypy
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WEB_CONCURRENCY=4

  granian-asgi:
    <<: *common
    build:
      context: python/granian
      dockerfile: Dockerfile.asgi
    environment:
      - DATABASE_URL=${DATABASE_URL}

  granian-rsgi:
    <<: *common
    build:
      context: python/granian
      dockerfile: Dockerfile.rsgi
    environment:
      - DATABASE_URL=${DATABASE_URL}

  fastapi:
    <<: *common
    build:
      context: python/fastapi
    environment:
      - DATABASE_URL=${DATABASE_URL}

  fastapi-sync-endpoints:
    <<: *common
    build:
      context: python/fastapi
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SYNC_ENDPOINTS=1

  fastapi-sync-dependency:
    <<: *common
    build:
      context: python/fastapi
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SYNC_DEPENDENCY=1

  django-sync-worker:
    <<: *common
    build:
      context: python/django
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - WORKER_CLASS=sync

  django-gthread-worker:
    <<: *common
    build:
      context: python/django
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - WORKER_CLASS=gthread
      - THREADS=10

  django-gevent-worker:
    <<: *common
    build:
      context: python/django
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - WORKER_CLASS=gevent

  django-asgi:
    <<: *common
    build:
      context: python/django
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - ASYNC_MODE=1

  robyn:
    <<: *common
    build:
      context: python/robyn
    environment:
      - DATABASE_URL=${DATABASE_URL}

  socketify-async:
    <<: *common
    build:
      context: python/socketify
    platform: linux/amd64
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SQL_DRIVER=asyncpg

  socketify-sync:
    <<: *common
    build:
      context: python/socketify
      dockerfile: Dockerfile.psycopg
    platform: linux/amd64
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SYNC_ENDPOINTS=1
      - SQL_DRIVER=psycopg_sync

  socketify-async-pypy:
    <<: *common
    build:
      context: python/socketify
      dockerfile: Dockerfile.psycopg_pypy
    platform: linux/amd64
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SQL_DRIVER=psycopg_async

  socketify-sync-pypy:
    <<: *common
    build:
      context: python/socketify
      dockerfile: Dockerfile.psycopg_pypy
    platform: linux/amd64
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SYNC_ENDPOINTS=1
      - SQL_DRIVER=psycopg_sync

  falcon-wsgi-sync-worker:
    <<: *common
    build:
      context: python/falcon
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WORKER_CLASS=sync

  falcon-wsgi-gthread-worker:
    <<: *common
    build:
      context: python/falcon
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WORKER_CLASS=gthread
      - THREADS=10

  falcon-wsgi-gevent-worker:
    <<: *common
    build:
      context: python/falcon
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WORKER_CLASS=gevent

  falcon-wsgi-sync-worker-pypy:
    <<: *common
    build:
      context: python/falcon
      dockerfile: Dockerfile.pypy
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WORKER_CLASS=sync

  falcon-wsgi-gthread-worker-pypy:
    <<: *common
    build:
      context: python/falcon
      dockerfile: Dockerfile.pypy
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WORKER_CLASS=gthread
      - THREADS=10

  falcon-wsgi-gevent-worker-pypy:
    <<: *common
    build:
      context: python/falcon
      dockerfile: Dockerfile.pypy
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WORKER_CLASS=gevent

  laravel:
    <<: *common
    build:
      context: php/laravel
      args:
        - POSTGRES_HOST=${POSTGRES_HOST}

  laravel-octane-franken:
    <<: *common
    build:
      context: php/laravel
      dockerfile: Dockerfile.octane-frankenphp
      args:
        - POSTGRES_HOST=${POSTGRES_HOST}

networks:
  default:
    name: webbench
    external: true
